/// Flutter icons Appetit
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Appetit
///      fonts:
///       - asset: fonts/Appetit.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Appetit {
  Appetit._();

  static const _kFontFam = 'Appetit';
  static const String _kFontPkg = null;

  static const IconData shopping_basket = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place_marker = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
